//
//  Constants.h
//  iPitbul
//
//  Created by Mykhailo Oleksiuk on 12/21/12.
//  Copyright (c) 2012 Mykhailo Oleksiuk. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const MANAGEMENT_ACTIONS;
FOUNDATION_EXPORT NSString *const MA_AM;
FOUNDATION_EXPORT NSString *const MA_DM;

FOUNDATION_EXPORT NSString *const SERVICE_ACTIONS;
FOUNDATION_EXPORT NSString *const SA_GM;
FOUNDATION_EXPORT NSString *const SA_ST;
FOUNDATION_EXPORT NSString *const SA_PW;
FOUNDATION_EXPORT NSString *const SA_ID;
FOUNDATION_EXPORT NSString *const SA_IM;
FOUNDATION_EXPORT NSString *const SA_GL;
FOUNDATION_EXPORT NSString *const SA_S1;
FOUNDATION_EXPORT NSString *const SA_S0;
FOUNDATION_EXPORT NSString *const SA_SM;

FOUNDATION_EXPORT NSString *const PITBUL_PHONE_NUMBER;
FOUNDATION_EXPORT NSString *const PITBUL_PASSWORD;

FOUNDATION_EXPORT NSString *const SETTINGS_CHANGED_NOTIFICATION;
FOUNDATION_EXPORT NSString *const PITBUL_ACTION_IN_NOTIFICATION;